import { readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { z } from "zod"

import { parseAttemptRows } from "@/lib/benchmarks/csv"
import { buildDashboardData, unique } from "@/lib/benchmarks/dashboard-build"
import { loadItems } from "@/lib/benchmarks/lichess-puzzles"
import type { LichessPuzzleAttemptRow } from "@/lib/benchmarks/local-runner"
import { MODELS, type ModelId } from "@/lib/benchmarks/models"

type Rgb = { r: number; g: number; b: number }
type Oklch = { l: number; c: number; h: number }
type SeriesColors = { color: string; colorDark: string }

type ModelsDevData = {
  labIds: string[]
  modelKeysByLowercase: Map<string, string>
}

const benchmarkId = "lichess-puzzles-v1"
const resultsDir = `data/results/canonical/${benchmarkId}`
const itemsPath = `data/benchmarks/${benchmarkId}/items.jsonl`
const manifestPath = `data/benchmarks/${benchmarkId}/manifest.json`
const outputPath = "lib/benchmarks/dashboard-data.ts"

/** `--card` in app/globals.css, light and dark. */
const LIGHT_SURFACE: Oklch = { l: 1, c: 0, h: 0 }
const DARK_SURFACE: Oklch = { l: 0.205, c: 0, h: 0 }
/** WCAG 1.4.11 asks 3:1 for graphical objects; the extra 0.5 is headroom. */
const SERIES_MIN_CONTRAST = 3.5
/**
 * A near-grey series has no hue to tell it apart, so it earns luminance
 * separation instead. This is also what the lab logos do: they invert.
 */
const NEUTRAL_SERIES_MIN_CONTRAST = 8
const ACHROMATIC_CHROMA = 0.04
const MIN_HUE_SEPARATION = 40

const allItems = await loadItems(itemsPath)
const modelsDev = await loadModelsDevData()
const rows: Record<ModelId, LichessPuzzleAttemptRow[]> = Object.fromEntries(
  await Promise.all(
    MODELS.map(async (model) => [
      model.id,
      parseAttemptRows(await readFile(join(resultsDir, model.file), "utf8")),
    ])
  )
)

const seriesColors = buildSeriesPalette(MODELS.map((model) => model.brand))
const data = buildDashboardData({
  models: MODELS.map(({ id, apiModel, name, vendor, releaseQ }, index) => ({
    id,
    name,
    vendor,
    lab: resolveModelLab(apiModel, modelsDev),
    ...seriesColors[index],
    releaseQ,
  })),
  items: allItems,
  rows,
  datasetSize: await loadDatasetSize(manifestPath, allItems.length),
  sourceFiles: MODELS.map((model) => model.file),
})

const contents = `// Generated by scripts/build-dashboard-data.ts from canonical benchmark CSVs.
// Do not edit this file by hand.

export type DashboardModelId = ${data.models.map((model) => JSON.stringify(model.id)).join(" | ")}
/**
 * Exactly the labs the configured models belong to, never the full models.dev
 * catalog: models.dev gains labs on its own schedule, and widening the union
 * from it would rewrite this file — and break the \`satisfies
 * Record<DashboardLabId, ...>\` check on \`LAB_SVGS\` — on any day a third party
 * shipped a lab nothing here uses. Derived this way the union only moves when
 * the model list moves, and the exhaustiveness check still fails the build when
 * a lab the dashboard *does* render has no logo.
 */
export type DashboardLabId = ${data.labIds.map((lab) => JSON.stringify(lab)).join(" | ")}
export type DashboardCategoryId = ${data.categories.map((category) => JSON.stringify(category.id)).join(" | ")}

export type DashboardModel = {
  id: DashboardModelId
  name: string
  /** Shortest word prefix of \`name\` that no other model shares, for tight labels. */
  shortName: string
  vendor: string
  lab: DashboardLabId
  /**
   * Chart series color for the light theme. Derived from the lab's brand hex:
   * hue is kept (rotated only to break a collision with an earlier series) and
   * lightness is moved until the color clears ${SERIES_MIN_CONTRAST}:1 against
   * the light \`--card\` surface, so it satisfies WCAG 1.4.11 as a graphical
   * object. Never assume the brand hex itself is safe on either surface.
   */
  color: string
  /** Same series, fitted to the dark \`--card\` surface. */
  colorDark: string
  releaseQ: string
}

export type DashboardScore = {
  model: DashboardModelId
  /** Puzzles this model was actually evaluated on. */
  n: number
  accuracy: number
  /** Derived from puzzle ratings and accuracy, not a played rating. */
  elo: number
  /** Where \`elo\` lands if the model misses (low) or solves (high) one more of its n puzzles. */
  eloLow: number
  eloHigh: number
  /** Extrapolated cost per 1,000 puzzles from the sampled rows. */
  cost: number
  avgTokens: number
  avgMoveTime: number
  legalRate: number
}

/**
 * Per-theme accuracy. \`accuracy\` is null when the sample contained no puzzle
 * in that bucket, so consumers must render an absence instead of a value.
 */
export type DashboardCategoryScore = { accuracy: number | null; n: number }

export type DashboardPuzzleItem = {
  id: string
  fen: string
  themes: DashboardCategoryId[]
  side: "w" | "b"
  rating: number
  popularity: number
  solution: string[]
  caption: string
  attempts: DashboardSolutionAttempt[]
}

export type DashboardSolutionAttempt = {
  model: DashboardModelId
  correct: boolean
  playedMove: string
  movePretty: string
  thinkingMs: number
  thinkingTokens: number
  transcript: string
}

export type DashboardMeta = {
  puzzleCount: number
  evaluations: number
  /** Distinct puzzles per model; a range when models were not run on the same count. */
  sampleSize: { min: number; max: number }
  datasetSize: number
  lastUpdated: string
  version: string
  benchmarkId: string
  sourceFiles: string[]
  rowsByModel: Record<DashboardModelId, number>
  /** Min and max puzzle rating, rounded outward to \`ratingStep\`. */
  ratingBounds: [number, number]
  ratingStep: number
  maxOutputTokens: string
  eloIsEstimated: boolean
  costIsExtrapolated: boolean
}

export const MODELS: DashboardModel[] = ${toTs(data.models)}

export const CATEGORIES: Array<{ id: DashboardCategoryId; label: string }> = ${toTs(data.categories)}

export const SCOREBOARD: DashboardScore[] = ${toTs(data.scoreboard)}

// accuracy null means the model had no evaluated puzzle in that theme bucket; it is not a score.
export const CATEGORY: Record<DashboardModelId, Record<DashboardCategoryId, DashboardCategoryScore>> = ${toTs(data.category)}

export const PUZZLES: DashboardPuzzleItem[] = ${toTs(data.puzzles)}

export const META: DashboardMeta = ${toTs(data.meta)}
`

await writeFile(outputPath, contents)
console.log(`Wrote dashboard data to ${outputPath}`)

/* ------------------------------------------------------------------ *
 * Series palette
 *
 * Brand hexes are authored per model above and are only guaranteed to be
 * correct, not legible: xAI ships a near-black, Google and DeepSeek ship two
 * blues 3 degrees apart. Rendering them unchanged puts an invisible line on the
 * dark card (#111827 measures 1.0:1 there) and two indistinguishable series on
 * both. The palette below is therefore derived, not copied, and the derivation
 * lives in the generator so a model added tomorrow gets the same treatment
 * without anyone remembering to update an override map in the UI.
 * ------------------------------------------------------------------ */

function buildSeriesPalette(brands: string[]): SeriesColors[] {
  const source = brands.map((hex) => rgbToOklch(hexToRgb(hex)))
  const hues = separateHues(source)

  return source.map((base, index) => {
    const neutral = base.c < ACHROMATIC_CHROMA
    const target = neutral ? NEUTRAL_SERIES_MIN_CONTRAST : SERIES_MIN_CONTRAST
    const seed: Oklch = { ...base, h: hues[index] ?? base.h }

    return {
      color: rgbToHex(fitContrast(seed, LIGHT_SURFACE, target)),
      colorDark: rgbToHex(fitContrast(seed, DARK_SURFACE, target)),
    }
  })
}

/**
 * A series keeps its brand hue unless an earlier series already occupies it.
 * When it has to move it takes the smallest rotation that clears every earlier
 * series and, where one exists, every later brand hue as well, so resolving one
 * collision does not shunt the next series out of its own brand.
 */
function separateHues(source: Oklch[]): Array<number | null> {
  const brandHues = source.map((color) =>
    color.c < ACHROMATIC_CHROMA ? null : color.h
  )
  const resolved: Array<number | null> = []

  for (const [index, own] of brandHues.entries()) {
    if (own == null) {
      resolved.push(null)
      continue
    }

    const earlier = resolved.filter((hue): hue is number => hue != null)
    const later = brandHues
      .slice(index + 1)
      .filter((hue): hue is number => hue != null)
    const clears = (hue: number, others: number[]) =>
      others.every((other) => hueDistance(hue, other) >= MIN_HUE_SEPARATION)

    if (clears(own, earlier)) {
      resolved.push(own)
      continue
    }

    let best: number | null = null
    let fallback: number | null = null

    for (let step = 1; step <= 180 && best == null; step += 1) {
      for (const direction of [-1, 1]) {
        const candidate = (own + direction * step + 360) % 360

        if (!clears(candidate, earlier)) {
          continue
        }

        fallback ??= candidate

        if (clears(candidate, later)) {
          best = candidate
          break
        }
      }
    }

    resolved.push(best ?? fallback ?? own)
  }

  return resolved
}

/** Moves lightness away from the surface until the contrast target is met. */
function fitContrast(color: Oklch, surface: Oklch, target: number): Rgb {
  const backdrop = oklchToRgb(surface)
  const step = surface.l > 0.5 ? -0.005 : 0.005
  let lightness = color.l

  for (let i = 0; i <= 220; i += 1) {
    const candidate = clampToGamut({ ...color, l: lightness })

    if (contrastRatio(candidate, backdrop) >= target) {
      return candidate
    }

    lightness += step

    if (lightness < 0 || lightness > 1) {
      break
    }
  }

  return clampToGamut({ ...color, l: Math.min(1, Math.max(0, lightness)) })
}

function hueDistance(a: number, b: number) {
  const delta = Math.abs(a - b) % 360
  return delta > 180 ? 360 - delta : delta
}

function srgbToLinear(value: number) {
  return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4
}

function linearToSrgb(value: number) {
  return value <= 0.0031308 ? value * 12.92 : 1.055 * value ** (1 / 2.4) - 0.055
}

function hexToRgb(hex: string): Rgb {
  const digits = hex.replace("#", "")
  const full =
    digits.length === 3
      ? digits
          .split("")
          .map((digit) => digit + digit)
          .join("")
      : digits

  return {
    r: Number.parseInt(full.slice(0, 2), 16) / 255,
    g: Number.parseInt(full.slice(2, 4), 16) / 255,
    b: Number.parseInt(full.slice(4, 6), 16) / 255,
  }
}

function rgbToHex({ r, g, b }: Rgb) {
  const channel = (value: number) =>
    Math.round(Math.min(1, Math.max(0, value)) * 255)
      .toString(16)
      .padStart(2, "0")

  return `#${channel(r)}${channel(g)}${channel(b)}`
}

function rgbToOklch({ r, g, b }: Rgb): Oklch {
  const lr = srgbToLinear(r)
  const lg = srgbToLinear(g)
  const lb = srgbToLinear(b)
  const long = Math.cbrt(
    0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb
  )
  const medium = Math.cbrt(
    0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb
  )
  const short = Math.cbrt(
    0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb
  )
  const lightness =
    0.2104542553 * long + 0.793617785 * medium - 0.0040720468 * short
  const greenRed =
    1.9779984951 * long - 2.428592205 * medium + 0.4505937099 * short
  const blueYellow =
    0.0259040371 * long + 0.7827717662 * medium - 0.808675766 * short
  const chroma = Math.hypot(greenRed, blueYellow)

  return {
    l: lightness,
    c: chroma,
    h:
      chroma < 1e-6
        ? 0
        : ((Math.atan2(blueYellow, greenRed) * 180) / Math.PI + 360) % 360,
  }
}

function oklchToRgb({ l, c, h }: Oklch): Rgb {
  const radians = (h * Math.PI) / 180
  const greenRed = c * Math.cos(radians)
  const blueYellow = c * Math.sin(radians)
  const long = (l + 0.3963377774 * greenRed + 0.2158037573 * blueYellow) ** 3
  const medium = (l - 0.1055613458 * greenRed - 0.0638541728 * blueYellow) ** 3
  const short = (l - 0.0894841775 * greenRed - 1.291485548 * blueYellow) ** 3

  return {
    r: linearToSrgb(
      4.0767416621 * long - 3.3077115913 * medium + 0.2309699292 * short
    ),
    g: linearToSrgb(
      -1.2684380046 * long + 2.6097574011 * medium - 0.3413193965 * short
    ),
    b: linearToSrgb(
      -0.0041960863 * long - 0.7034186147 * medium + 1.707614701 * short
    ),
  }
}

function inGamut({ r, g, b }: Rgb) {
  return [r, g, b].every((value) => value >= -1e-4 && value <= 1 + 1e-4)
}

/** Bisects chroma down until the color is representable in sRGB. */
function clampToGamut(color: Oklch): Rgb {
  if (inGamut(oklchToRgb(color))) {
    return oklchToRgb(color)
  }

  let low = 0
  let high = color.c

  for (let i = 0; i < 40; i += 1) {
    const mid = (low + high) / 2

    if (inGamut(oklchToRgb({ ...color, c: mid }))) {
      low = mid
    } else {
      high = mid
    }
  }

  return oklchToRgb({ ...color, c: low })
}

function relativeLuminance({ r, g, b }: Rgb) {
  const channel = (value: number) =>
    srgbToLinear(Math.min(1, Math.max(0, value)))

  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)
}

function contrastRatio(a: Rgb, b: Rgb) {
  const first = relativeLuminance(a)
  const second = relativeLuminance(b)

  return (Math.max(first, second) + 0.05) / (Math.min(first, second) + 0.05)
}

async function loadModelsDevData(): Promise<ModelsDevData> {
  const response = await fetch("https://models.dev/models.json")

  if (!response.ok) {
    throw new Error(
      `Unable to load models.dev model catalog: ${response.status} ${response.statusText}`
    )
  }

  const catalog = z.record(z.string(), z.unknown()).parse(await response.json())
  const modelKeys = Object.keys(catalog)
  const labIds = unique(modelKeys.map((key) => key.split("/")[0] ?? ""))
    .filter(Boolean)
    .sort()

  if (labIds.length === 0) {
    throw new Error(
      "models.dev model catalog did not contain lab-prefixed keys"
    )
  }

  return {
    labIds,
    modelKeysByLowercase: new Map(
      modelKeys.map((key) => [key.toLowerCase(), key])
    ),
  }
}

function resolveModelLab(apiModel: string, modelsDev: ModelsDevData): string {
  const lab = apiModel.split("/")[0]?.toLowerCase()

  if (!lab || !modelsDev.labIds.includes(lab)) {
    throw new Error(
      `Unable to resolve models.dev lab for ${apiModel}. Expected the model id to start with a known models.dev lab id.`
    )
  }

  const matchedKey = modelKeyCandidates(apiModel).find((candidate) =>
    modelsDev.modelKeysByLowercase.has(candidate.toLowerCase())
  )

  if (!matchedKey) {
    console.warn(
      `No exact models.dev model key found for ${apiModel}; using validated lab prefix ${lab}.`
    )
  }

  return lab
}

function modelKeyCandidates(apiModel: string): string[] {
  const [lab = "", slug = ""] = apiModel.split("/")
  const slugCandidates = unique([
    slug,
    slug.replace(/\.(?=\d)/g, "-"),
    slug.replace(/-(thinking|reasoning|non-reasoning)$/i, ""),
    slug
      .replace(/-(thinking|reasoning|non-reasoning)$/i, "")
      .replace(/\.(?=\d)/g, "-"),
  ]).filter(Boolean)

  return slugCandidates.map((candidate) => `${lab}/${candidate}`)
}

async function loadDatasetSize(path: string, itemCount: number) {
  const manifestSchema = z.object({
    selection: z.object({ totalItems: z.number().optional() }).optional(),
  })
  const manifest = manifestSchema.parse(
    JSON.parse(await readFile(path, "utf8"))
  )
  const declared = manifest.selection?.totalItems

  if (declared === undefined) {
    return itemCount
  }

  if (declared !== itemCount) {
    console.warn(
      `Manifest totalItems (${declared}) does not match ${itemsPath} row count (${itemCount}); using the row count.`
    )
    return itemCount
  }

  return declared
}

function toTs<T>(value: T) {
  return JSON.stringify(value, null, 2)
}
